/**
 * CSS class names for use in components
 */
export const classNames = {
  container: 'agentary-container',
  overlay: 'agentary-overlay',
  floatingButton: 'agentary-floating-button',
  floatingButtonContainer: 'agentary-floating-button-container',
  floatingButtonReady: 'agentary-ready-pulse',
  speechBubble: 'agentary-speech-bubble',
  speechBubbleContent: 'agentary-speech-bubble-content',
  speechBubbleArrow: 'agentary-speech-bubble-arrow',
  spinner: 'agentary-spinner',
  fadeIn: 'agentary-fade-in',
  fadeOut: 'agentary-fade-out',
  popup: 'agentary-popup',
  slideIn: 'agentary-slide-in',
  slideOut: 'agentary-slide-out',
  header: 'agentary-header',
  headerContent: 'agentary-header-content',
  headerIcon: 'agentary-header-icon',
  headerTitle: 'agentary-header-title',
  closeButton: 'agentary-close-button',
  content: 'agentary-content',
  contentIcon: 'agentary-content-icon',
  contentTitle: 'agentary-content-title',
  contentDescription: 'agentary-content-description',
  featureNotice: 'agentary-feature-notice',
  featureIcon: 'agentary-feature-icon',
  questionInputContainer: 'agentary-question-input-container',
  inputRow: 'agentary-input-row',
  questionInput: 'agentary-question-input',
  footer: 'agentary-footer',
  sendButton: 'agentary-send-button',
  promptPillsContainer: 'agentary-prompt-pills-container',
  actionPromptsContainer: 'agentary-action-prompts-container',
  promptPill: 'agentary-prompt-pill',
  contentPromptSection: 'agentary-content-prompt-section',
  contentPromptLabel: 'agentary-content-prompt-label',
  contentPromptPill: 'agentary-content-prompt-pill',
  contentPromptToggle: 'agentary-content-prompt-toggle',
  expandablePrompts: 'agentary-expandable-prompts',
  expanded: 'agentary-expanded',
  contentPromptCount: 'agentary-content-prompt-count',
  // Chat interface classes
  chatContainer: 'agentary-chat-container',
  chatHeader: 'agentary-chat-header',
  chatBackButton: 'agentary-chat-back-button',
  chatHeaderContent: 'agentary-chat-header-content',
  chatTitle: 'agentary-chat-title',
  chatSubtitle: 'agentary-chat-subtitle',
  chatMessages: 'agentary-chat-messages',
  chatMessage: 'agentary-chat-message',
  chatMessageUser: 'agentary-chat-message-user',
  chatMessageAssistant: 'agentary-chat-message-assistant',
  chatMessageContent: 'agentary-chat-message-content',
  chatMessageTime: 'agentary-chat-message-time',
  chatTypingIndicator: 'agentary-chat-typing-indicator',
  chatInputContainer: 'agentary-chat-input-container',
  chatInputRow: 'agentary-chat-input-row',
  chatInput: 'agentary-chat-input',
  chatSendButton: 'agentary-chat-send-button',
  // Streaming classes
  streamingCursor: 'agentary-streaming-cursor',
  // Related articles classes
  relatedArticles: 'agentary-related-articles',
  relatedArticlesWrapper: 'agentary-related-articles-wrapper',
  relatedArticlesHeader: 'agentary-related-articles-header',
  relatedArticlesCarousel: 'agentary-related-articles-carousel',
  relatedArticlesContainer: 'agentary-related-articles-container',
  relatedArticleCard: 'agentary-related-article-card',
  relatedArticleImageBg: 'agentary-related-article-image-bg',
  relatedArticleOverlay: 'agentary-related-article-overlay',
  relatedArticleContent: 'agentary-related-article-content',
  relatedArticleTitle: 'agentary-related-article-title',
  relatedArticleSummary: 'agentary-related-article-summary',
  relatedArticleSource: 'agentary-related-article-source',
  relatedArticlesNavigation: 'agentary-related-articles-navigation',
  relatedArticlesDots: 'agentary-related-articles-dots',
  relatedArticlesDot: 'agentary-related-articles-dot',
  active: 'agentary-active',
  // Skeleton loading classes
  skeleton: 'agentary-skeleton',
  skeletonArticle: 'agentary-skeleton-article',
  skeletonArticleBg: 'agentary-skeleton-article-bg',
  skeletonContent: 'agentary-skeleton-content',
  skeletonTitle: 'agentary-skeleton-title',
  skeletonTitleShort: 'agentary-skeleton-title-short',
  skeletonSource: 'agentary-skeleton-source',
  // Fade-in animation class
  articlesFadeIn: 'agentary-articles-fade-in',
  // Scroll indicator
  scrollIndicator: 'agentary-scroll-indicator',
  summaryScrollIndicator: 'agentary-summary-scroll-indicator',
  // Footer gradient
  footerGradient: 'agentary-footer-gradient',
}; 